class_name AssetRegistry
extends RefCounted
## Central registry of every Blender-generated mesh bundled with the game.
##
## `assets/meshes/` holds plain glTF binaries (`<key>.glb`) that Godot imports
## natively — no plugin, no conversion step. Games reference the logical *key*,
## never a path, so one mesh can be reused across games and a file can be
## regenerated by the Blender scripts without touching a single line of code.
##
## The walk-in mesh gallery in the lobby iterates this table, which is why every
## bundled mesh shows up there automatically. A unit test keeps `KEYS` and the
## folder in sync in both directions.

const MESH_DIR := "res://assets/meshes"

## Every bundled mesh key, alphabetically.
const KEYS: Array[String] = [
	"candy/bonbon",
	"candy/chocolate",
	"candy/daisy",
	"candy/gift",
	"candy/gumdrop",
	"candy/heart",
	"candy/jellybean",
	"candy/lily",
	"candy/lolly",
	"candy/lotus",
	"candy/rose",
	"candy/sunflower",
	"candy/tulip",
	"crystal",
	"crystal1",
	"crystal2",
	"crystal3",
	"crystal4",
	"crystal5",
	"fence",
	"flight/ballista",
	"flight/cloud",
	"flight/cloud_storm",
	"flight/dragon_cloud",
	"flight/dragon_solar",
	"flight/dragon_tide",
	"flight/dragon_void",
	"flight/egg",
	"flight/egg_crystal",
	"flight/egg_large",
	"flight/fireball",
	"flight/golem",
	"flight/harpy",
	"flight/imp",
	"flight/island",
	"flight/nest",
	"flight/pedestal",
	"flight/roost",
	"flight/totem",
	"flight/wyvern",
	"halloween_candy",
	"halloween_ghost_pumpkin",
	"halloween_mini_pumpkin",
	"halloween_pumpkin",
	"halloween_seed",
	"horse",
	"log",
	"metro/bridge",
	"metro/car",
	"metro/house",
	"metro/interchange",
	"metro/loco",
	"metro/park",
	"metro/passenger",
	"metro/station",
	"metro/tower",
	"metro/transfer_ring",
	"metro/tunnel_portal",
	"ornament",
	"pang/clock",
	"pang/harpoon",
	"pang/heart",
	"pang/ice",
	"pang/orb",
	"pang/platform",
	"pumpkin",
	"rock",
	"rpg/amulet",
	"rpg/armor",
	"rpg/axe",
	"rpg/barrel",
	"rpg/bone_pile",
	"rpg/boots",
	"rpg/bow",
	"rpg/broken_pillar",
	"rpg/bush",
	"rpg/campfire",
	"rpg/chest",
	"rpg/coin",
	"rpg/crate",
	"rpg/crown",
	"rpg/crystal_cluster",
	"rpg/dagger",
	"rpg/dead_tree",
	"rpg/dragon_bone",
	"rpg/dragon_crystal",
	"rpg/dragon_elder",
	"rpg/dragon_ember",
	"rpg/dragon_frost",
	"rpg/dragon_gold",
	"rpg/dragon_hatchling",
	"rpg/dragon_lord",
	"rpg/dragon_shadow",
	"rpg/dragon_stone",
	"rpg/dragon_storm",
	"rpg/dragon_venom",
	"rpg/dungeon_arch",
	"rpg/gem",
	"rpg/grass_tuft",
	"rpg/gravestone",
	"rpg/greatsword",
	"rpg/helmet",
	"rpg/key",
	"rpg/knight",
	"rpg/mushroom",
	"rpg/pine_tree",
	"rpg/portal_gate",
	"rpg/potion_health",
	"rpg/potion_mana",
	"rpg/ring",
	"rpg/rock_large",
	"rpg/rock_small",
	"rpg/rune_stone",
	"rpg/scroll",
	"rpg/shield",
	"rpg/skull",
	"rpg/staff",
	"rpg/stalagmite",
	"rpg/stone_pillar",
	"rpg/sword",
	"rpg/torch",
	"siedler/bakery",
	"siedler/blacksmith",
	"siedler/castle",
	"siedler/coal_mine",
	"siedler/coal_node",
	"siedler/construction",
	"siedler/farm",
	"siedler/fishery",
	"siedler/flag",
	"siedler/fish_spot",
	"siedler/forester",
	"siedler/gold_mine",
	"siedler/gold_node",
	"siedler/iron_mine",
	"siedler/iron_node",
	"siedler/knight",
	"siedler/oak",
	"siedler/quarry",
	"siedler/sawmill",
	"siedler/settler",
	"siedler/smelter",
	"siedler/stone_node",
	"siedler/toolsmith",
	"siedler/warehouse",
	"siedler/watchtower",
	"siedler/windmill",
	"siedler/woodcutter",
	"ship",
	"tree",
	"xmas_bauble",
	"xmas_candy_cane",
	"xmas_gingerbread_star",
	"xmas_pinecone",
	"xmas_star",
]

## Sections of the gallery, in walking order.
const GROUPS: Array[Dictionary] = [
	{"id": "helden", "name": "Heroes & weapons", "icon": "⚔", "color": Color("94a3b8")},
	{"id": "drachen", "name": "Dragons", "icon": "☄", "color": Color("f472b6")},
	{"id": "metro", "name": "City & Metro", "icon": "▣", "color": Color("38bdf8")},
	{"id": "sammeln", "name": "Loot & gear", "icon": "◆", "color": Color("fbbf24")},
	{"id": "natur", "name": "Nature", "icon": "❦", "color": Color("4ade80")},
	{"id": "ruinen", "name": "Ruins & props", "icon": "▣", "color": Color("a78bfa")},
	{"id": "zucht", "name": "Breeding & eggs", "icon": "✦", "color": Color("f472b6")},
	{"id": "gegner", "name": "Enemies", "icon": "◉", "color": Color("f87171")},
	{"id": "pang", "name": "Pang objects", "icon": "⇈", "color": Color("fbbf24")},
	{"id": "merge", "name": "Merge & crystal tiers", "icon": "✦", "color": Color("38bdf8")},
	{"id": "siedler", "name": "Settler village", "icon": "⌂", "color": Color("84cc16")},
	{"id": "candy", "name": "Candy crush tiles", "icon": "✦", "color": Color("f472b6")},
]

## Breeding props of the hatchery.
const ZUCHT_KEYS: Array[String] = [
	"flight/egg", "flight/egg_large", "flight/egg_crystal",
	"flight/nest", "flight/pedestal", "flight/roost",
]

## Flying and ground enemies of the dragon-flight game.
const GEGNER_KEYS: Array[String] = [
	"flight/wyvern", "flight/imp", "flight/harpy", "flight/ballista", "flight/golem",
]

## Ball, harpoon, platform and the three bonus pickups of the Pang clone.
const PANG_KEYS: Array[String] = [
	"pang/orb", "pang/harpoon", "pang/platform",
	"pang/ice", "pang/clock", "pang/heart",
]

const MERGE_KEYS: Array[String] = [
	"crystal", "crystal1", "crystal2", "crystal3", "crystal4", "crystal5",
	"ornament", "pumpkin",
	"xmas_pinecone", "xmas_candy_cane", "xmas_bauble", "xmas_gingerbread_star", "xmas_star",
	"halloween_seed", "halloween_candy", "halloween_mini_pumpkin", "halloween_pumpkin", "halloween_ghost_pumpkin",
]

## Board pieces of the match-3 (candy + flower world plus one Xmas prop).
const CANDY_KEYS: Array[String] = [
	"candy/bonbon", "candy/lolly", "candy/jellybean",
	"candy/gumdrop", "candy/chocolate", "candy/heart",
	"candy/rose", "candy/tulip", "candy/sunflower",
	"candy/daisy", "candy/lily", "candy/lotus", "candy/gift",
]

const NATURE_KEYS: Array[String] = [
	"rpg/pine_tree", "rpg/dead_tree", "rpg/bush", "rpg/grass_tuft", "rpg/mushroom",
	"rpg/crystal_cluster", "rpg/stalagmite", "tree",
]

const TREASURE_KEYS: Array[String] = [
	"rpg/coin", "rpg/gem", "rpg/ring", "rpg/amulet", "rpg/shield", "rpg/helmet",
	"rpg/armor", "rpg/boots", "rpg/crown", "rpg/scroll", "rpg/key",
	"rpg/chest", "rpg/barrel", "rpg/crate", "rpg/potion_health", "rpg/potion_mana",
	"rpg/campfire", "rpg/torch",
]

const RUIN_KEYS: Array[String] = [
	"rpg/stone_pillar", "rpg/broken_pillar", "rpg/rune_stone", "rpg/gravestone",
	"rpg/dungeon_arch", "rpg/portal_gate", "rpg/skull", "rpg/bone_pile",
	"rpg/rock_small", "rpg/rock_large", "rock", "log", "fence",
]

## Buildings, rolling stock and infrastructure of the metro game.
const METRO_KEYS: Array[String] = [
	"metro/station", "metro/interchange", "metro/transfer_ring", "metro/loco",
	"metro/car", "metro/bridge", "metro/tunnel_portal", "metro/house",
	"metro/tower", "metro/park", "metro/passenger",
]

## Castle, production buildings, road flags, settlers and deposits of the
## Siedler game.
const SIEDLER_KEYS: Array[String] = [
	"siedler/castle", "siedler/warehouse", "siedler/construction", "siedler/flag",
	"siedler/settler", "siedler/knight",
	"siedler/woodcutter", "siedler/forester", "siedler/sawmill", "siedler/quarry",
	"siedler/farm", "siedler/windmill", "siedler/bakery", "siedler/fishery",
	"siedler/coal_mine", "siedler/iron_mine", "siedler/gold_mine", "siedler/smelter",
	"siedler/toolsmith", "siedler/blacksmith", "siedler/watchtower",
	"siedler/oak", "siedler/stone_node", "siedler/coal_node", "siedler/iron_node",
	"siedler/gold_node", "siedler/fish_spot",
]


# --- detail levels ----------------------------------------------------------
#
# Every mesh ships in three resolutions. `low` is the one the games use (a few
# hundred triangles, so the APK and every mobile GPU stay happy); `med` and
# `high` are generated from the same geometry by
# `scripts/blender/generate_lod_meshes.py` and exist for the mesh gallery, where
# you can compare a silhouette against a properly detailed version.
#
# Only the low tier is in the registry's `KEYS`; the richer tiers are derived, so
# adding a mesh automatically gives it all three levels.

const TIERS: Array[String] = ["low", "med", "high"]

## What the gallery calls the tiers, plus the triangle budget each one aims for.
const TIER_LABELS := {
	"low": "Low Poly",
	"med": "Mittel",
	"high": "Hoch",
}

const TIER_BUDGET := {"low": 0, "med": 1000, "high": 10000}

## Written by the Blender LOD generator; `{"<key>": {"low": n, "med": n, "high": n}}`.
const LOD_STATS := "%s/lod.json" % MESH_DIR

static var _tri_cache: Dictionary = {}
static var _tri_cache_loaded := false


## `res://` path of a mesh.
static func path_of(key: String) -> String:
	return "%s/%s.glb" % [MESH_DIR, key]


## `res://` path of one detail level. The low tier lives in the mesh root, the
## generated tiers in their own folders.
static func tier_path_of(key: String, tier: String) -> String:
	if tier == "low" or tier == "":
		return path_of(key)
	return "%s/%s/%s.glb" % [MESH_DIR, tier, key]


## True when the mesh is bundled and imported.
static func exists(key: String) -> bool:
	return ResourceLoader.exists(path_of(key))


## True when one detail level is available. A key always has `low`; the richer
## tiers only exist once the generator has run.
static func tier_exists(key: String, tier: String) -> bool:
	return ResourceLoader.exists(tier_path_of(key, tier))


## The finest level that is actually present, never finer than `tier`.
static func best_available(key: String, tier: String) -> String:
	for candidate in TIERS:
		if TIERS.find(candidate) < TIERS.find(tier) and tier_exists(key, candidate):
			return candidate
	return "low"


## Measured triangle counts per key, read once from the generator's stats file.
static func tri_counts() -> Dictionary:
	if _tri_cache_loaded:
		return _tri_cache
	_tri_cache_loaded = true
	_tri_cache = {}
	if not FileAccess.file_exists(LOD_STATS):
		return _tri_cache
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(LOD_STATS))
	if parsed is Dictionary:
		for key in parsed:
			_tri_cache[str(key)] = (parsed as Dictionary)[key]
	return _tri_cache


## Triangle count of one level, or -1 when the generator has not run.
static func tri_count(key: String, tier: String) -> int:
	var entry: Variant = tri_counts().get(key)
	if not (entry is Dictionary):
		return -1
	return int((entry as Dictionary).get(tier, -1))


## `1.240 Dreiecke`, or an em dash when the count is unknown.
static func tri_text(key: String, tier: String) -> String:
	var count := tri_count(key, tier)
	return "—" if count < 0 else Ui.format_number(count)


## German display name for a key, derived from the file name.
static func display_name(key: String) -> String:
	var raw := key.get_file().replace("_", " ")
	var words := raw.split(" ")
	for i in words.size():
		words[i] = words[i].capitalize()
	return " ".join(words)


## Which gallery section a key belongs to.
static func group_of(key: String) -> String:
	if key.begins_with("rpg/dragon_") or key.begins_with("flight/dragon_"):
		return "drachen"
	if key in ZUCHT_KEYS:
		return "zucht"
	if key in METRO_KEYS:
		return "metro"
	if key in SIEDLER_KEYS:
		return "siedler"
	if key in GEGNER_KEYS:
		return "gegner"
	if key in PANG_KEYS:
		return "pang"
	if key in ["rpg/knight", "horse", "rpg/sword", "rpg/greatsword", "rpg/dagger", "rpg/axe", "rpg/staff", "rpg/bow", "ship"]:
		return "helden"
	if key in CANDY_KEYS:
		return "candy"
	if key in MERGE_KEYS:
		return "merge"
	if key in NATURE_KEYS:
		return "natur"
	if key in TREASURE_KEYS:
		return "sammeln"
	if key in RUIN_KEYS:
		return "ruinen"
	# Everything else in the flight pack is sky scenery (clouds, islands, totems).
	if key.begins_with("flight/"):
		return "natur"
	return "helden"


## Keys of one section, in registry order.
static func keys_in_group(group_id: String) -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if group_of(key) == group_id:
			out.append(key)
	return out


## A stable colour per key, so every mesh looks the same everywhere.
static func color_of(key: String) -> Color:
	var text := key
	var hash := 0
	for i in text.length():
		hash = (hash * 31 + text.unicode_at(i)) & 0x7FFFFFFF
	var hue := float(hash % 360) / 360.0
	return Color.from_hsv(hue, 0.55, 0.95)


## Keys the registry promises but the folder does not deliver.
static func missing() -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if not exists(key):
			out.append(key)
	return out


## Meshes present on disk that the registry forgot.
static func unlisted() -> Array[String]:
	var out: Array[String] = []
	for key in _on_disk():
		if not (key in KEYS):
			out.append(key)
	return out


## Every `.glb` key found in the mesh folder, ignoring the generated tier
## folders — those mirror the low tier and are not separate meshes.
static func _on_disk() -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open(MESH_DIR)
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir():
			if not name.begins_with(".") and not (name in TIERS):
				out.append_array(_sub_keys(name))
		elif name.ends_with(".glb"):
			out.append(name.substr(0, name.length() - 4))
		name = dir.get_next()
	dir.list_dir_end()
	out.sort()
	return out


static func _sub_keys(folder: String) -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open("%s/%s" % [MESH_DIR, folder])
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if not dir.current_is_dir() and name.ends_with(".glb"):
			out.append("%s/%s" % [folder, name.substr(0, name.length() - 4)])
		name = dir.get_next()
	dir.list_dir_end()
	return out


## Keys whose richer tiers are missing, `[]` once the generator has run.
static func tiers_missing(tier: String) -> Array[String]:
	var out: Array[String] = []
	if tier == "low" or not (tier in TIERS):
		return out
	for key in KEYS:
		if not tier_exists(key, tier):
			out.append(key)
	return out
