class_name AssetRegistry
extends RefCounted
## Central registry of every Blender-generated mesh bundled with the game.
##
## `assets/meshes/` holds plain glTF binaries (`<key>.glb`) that Godot imports
## natively — no plugin, no conversion step. Games reference the logical *key*,
## never a path, so one mesh can be reused across games and a file can be
## regenerated by the Blender scripts without touching a single line of code.
##
## The walk-in mesh gallery in the lobby iterates this table, which is why every
## bundled mesh shows up there automatically. A unit test keeps `KEYS` and the
## folder in sync in both directions.

const MESH_DIR := "res://assets/meshes"

## Every bundled mesh key, alphabetically.
const KEYS: Array[String] = [
	"crystal",
	"crystal1",
	"crystal2",
	"crystal3",
	"crystal4",
	"crystal5",
	"fence",
	"halloween_candy",
	"halloween_ghost_pumpkin",
	"halloween_mini_pumpkin",
	"halloween_pumpkin",
	"halloween_seed",
	"horse",
	"log",
	"ornament",
	"pumpkin",
	"rock",
	"rpg/amulet",
	"rpg/armor",
	"rpg/axe",
	"rpg/barrel",
	"rpg/bone_pile",
	"rpg/boots",
	"rpg/bow",
	"rpg/broken_pillar",
	"rpg/bush",
	"rpg/campfire",
	"rpg/chest",
	"rpg/coin",
	"rpg/crate",
	"rpg/crown",
	"rpg/crystal_cluster",
	"rpg/dagger",
	"rpg/dead_tree",
	"rpg/dragon_bone",
	"rpg/dragon_crystal",
	"rpg/dragon_elder",
	"rpg/dragon_ember",
	"rpg/dragon_frost",
	"rpg/dragon_gold",
	"rpg/dragon_hatchling",
	"rpg/dragon_lord",
	"rpg/dragon_shadow",
	"rpg/dragon_stone",
	"rpg/dragon_storm",
	"rpg/dragon_venom",
	"rpg/dungeon_arch",
	"rpg/gem",
	"rpg/grass_tuft",
	"rpg/gravestone",
	"rpg/greatsword",
	"rpg/helmet",
	"rpg/key",
	"rpg/knight",
	"rpg/mushroom",
	"rpg/pine_tree",
	"rpg/portal_gate",
	"rpg/potion_health",
	"rpg/potion_mana",
	"rpg/ring",
	"rpg/rock_large",
	"rpg/rock_small",
	"rpg/rune_stone",
	"rpg/scroll",
	"rpg/shield",
	"rpg/skull",
	"rpg/staff",
	"rpg/stalagmite",
	"rpg/stone_pillar",
	"rpg/sword",
	"rpg/torch",
	"ship",
	"tree",
	"xmas_bauble",
	"xmas_candy_cane",
	"xmas_gingerbread_star",
	"xmas_pinecone",
	"xmas_star",
]

## Sections of the gallery, in walking order.
const GROUPS: Array[Dictionary] = [
	{"id": "helden", "name": "Helden & Waffen", "icon": "⚔", "color": Color("94a3b8")},
	{"id": "drachen", "name": "Drachen", "icon": "☄", "color": Color("f472b6")},
	{"id": "sammeln", "name": "Beute & Ausrüstung", "icon": "◆", "color": Color("fbbf24")},
	{"id": "natur", "name": "Natur", "icon": "❦", "color": Color("4ade80")},
	{"id": "ruinen", "name": "Ruinen & Props", "icon": "▣", "color": Color("a78bfa")},
	{"id": "merge", "name": "Merge- & Kristallstufen", "icon": "✦", "color": Color("38bdf8")},
]

const MERGE_KEYS: Array[String] = [
	"crystal", "crystal1", "crystal2", "crystal3", "crystal4", "crystal5",
	"ornament", "pumpkin",
	"xmas_pinecone", "xmas_candy_cane", "xmas_bauble", "xmas_gingerbread_star", "xmas_star",
	"halloween_seed", "halloween_candy", "halloween_mini_pumpkin", "halloween_pumpkin", "halloween_ghost_pumpkin",
]

const NATURE_KEYS: Array[String] = [
	"rpg/pine_tree", "rpg/dead_tree", "rpg/bush", "rpg/grass_tuft", "rpg/mushroom",
	"rpg/crystal_cluster", "rpg/stalagmite", "tree",
]

const TREASURE_KEYS: Array[String] = [
	"rpg/coin", "rpg/gem", "rpg/ring", "rpg/amulet", "rpg/shield", "rpg/helmet",
	"rpg/armor", "rpg/boots", "rpg/crown", "rpg/scroll", "rpg/key",
	"rpg/chest", "rpg/barrel", "rpg/crate", "rpg/potion_health", "rpg/potion_mana",
	"rpg/campfire", "rpg/torch",
]

const RUIN_KEYS: Array[String] = [
	"rpg/stone_pillar", "rpg/broken_pillar", "rpg/rune_stone", "rpg/gravestone",
	"rpg/dungeon_arch", "rpg/portal_gate", "rpg/skull", "rpg/bone_pile",
	"rpg/rock_small", "rpg/rock_large", "rock", "log", "fence",
]


## `res://` path of a mesh.
static func path_of(key: String) -> String:
	return "%s/%s.glb" % [MESH_DIR, key]


## True when the mesh is bundled and imported.
static func exists(key: String) -> bool:
	return ResourceLoader.exists(path_of(key))


## German display name for a key, derived from the file name.
static func display_name(key: String) -> String:
	var raw := key.get_file().replace("_", " ")
	var words := raw.split(" ")
	for i in words.size():
		words[i] = words[i].capitalize()
	return " ".join(words)


## Which gallery section a key belongs to.
static func group_of(key: String) -> String:
	if key.begins_with("rpg/dragon_"):
		return "drachen"
	if key in ["rpg/knight", "horse", "rpg/sword", "rpg/greatsword", "rpg/dagger", "rpg/axe", "rpg/staff", "rpg/bow", "ship"]:
		return "helden"
	if key in MERGE_KEYS:
		return "merge"
	if key in NATURE_KEYS:
		return "natur"
	if key in TREASURE_KEYS:
		return "sammeln"
	if key in RUIN_KEYS:
		return "ruinen"
	return "helden"


## Keys of one section, in registry order.
static func keys_in_group(group_id: String) -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if group_of(key) == group_id:
			out.append(key)
	return out


## A stable colour per key, so every mesh looks the same everywhere.
static func color_of(key: String) -> Color:
	var text := key
	var hash := 0
	for i in text.length():
		hash = (hash * 31 + text.unicode_at(i)) & 0x7FFFFFFF
	var hue := float(hash % 360) / 360.0
	return Color.from_hsv(hue, 0.55, 0.95)


## Keys the registry promises but the folder does not deliver.
static func missing() -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if not exists(key):
			out.append(key)
	return out


## Meshes present on disk that the registry forgot.
static func unlisted() -> Array[String]:
	var out: Array[String] = []
	for key in _on_disk():
		if not (key in KEYS):
			out.append(key)
	return out


## Every `.glb` key found in the mesh folder.
static func _on_disk() -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open(MESH_DIR)
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir():
			if not name.begins_with("."):
				out.append_array(_sub_keys(name))
		elif name.ends_with(".glb"):
			out.append(name.substr(0, name.length() - 4))
		name = dir.get_next()
	dir.list_dir_end()
	out.sort()
	return out


static func _sub_keys(folder: String) -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open("%s/%s" % [MESH_DIR, folder])
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if not dir.current_is_dir() and name.ends_with(".glb"):
			out.append("%s/%s" % [folder, name.substr(0, name.length() - 4)])
		name = dir.get_next()
	dir.list_dir_end()
	return out
