class_name AssetRegistry
extends RefCounted
## Central registry of every Blender-generated mesh bundled with the game.
##
## `assets/meshes/` holds plain glTF binaries (`<key>.glb`) that Godot imports
## natively — no plugin, no conversion step. Games reference the logical *key*,
## never a path, so one mesh can be reused across games and a file can be
## regenerated by the Blender scripts without touching a single line of code.
##
## The walk-in mesh gallery in the lobby iterates this table, which is why every
## bundled mesh shows up there automatically. A unit test keeps `KEYS` and the
## folder in sync in both directions.

const MESH_DIR := "res://assets/meshes"

## Every bundled mesh key, alphabetically.
const KEYS: Array[String] = [
	"candy/bonbon",
	"candy/chocolate",
	"candy/daisy",
	"candy/gift",
	"candy/gumdrop",
	"candy/heart",
	"candy/jellybean",
	"candy/lily",
	"candy/lolly",
	"candy/lotus",
	"candy/rose",
	"candy/sunflower",
	"candy/tulip",
	"crystal",
	"crystal1",
	"crystal2",
	"crystal3",
	"crystal4",
	"crystal5",
	"fence",
	"flight/ballista",
	"flight/cloud",
	"flight/cloud_storm",
	"flight/dragon_cloud",
	"flight/dragon_solar",
	"flight/dragon_tide",
	"flight/dragon_void",
	"flight/egg",
	"flight/egg_crystal",
	"flight/egg_large",
	"flight/fireball",
	"flight/golem",
	"flight/harpy",
	"flight/imp",
	"flight/island",
	"flight/nest",
	"flight/pedestal",
	"flight/roost",
	"flight/totem",
	"flight/wyvern",
	"halloween_candy",
	"halloween_ghost_pumpkin",
	"halloween_mini_pumpkin",
	"halloween_pumpkin",
	"halloween_seed",
	"horse",
	"log",
	"metro/bridge",
	"metro/car",
	"metro/house",
	"metro/interchange",
	"metro/loco",
	"metro/park",
	"metro/passenger",
	"metro/station",
	"metro/tower",
	"metro/transfer_ring",
	"metro/tunnel_portal",
	"ornament",
	"pang/clock",
	"pang/harpoon",
	"pang/heart",
	"pang/ice",
	"pang/orb",
	"pang/platform",
	"pumpkin",
	"rock",
	"rpg/amulet",
	"rpg/armor",
	"rpg/axe",
	"rpg/barrel",
	"rpg/bone_pile",
	"rpg/boots",
	"rpg/bow",
	"rpg/broken_pillar",
	"rpg/bush",
	"rpg/campfire",
	"rpg/chest",
	"rpg/coin",
	"rpg/crate",
	"rpg/crown",
	"rpg/crystal_cluster",
	"rpg/dagger",
	"rpg/dead_tree",
	"rpg/dragon_bone",
	"rpg/dragon_crystal",
	"rpg/dragon_elder",
	"rpg/dragon_ember",
	"rpg/dragon_frost",
	"rpg/dragon_gold",
	"rpg/dragon_hatchling",
	"rpg/dragon_lord",
	"rpg/dragon_shadow",
	"rpg/dragon_stone",
	"rpg/dragon_storm",
	"rpg/dragon_venom",
	"rpg/dungeon_arch",
	"rpg/gem",
	"rpg/grass_tuft",
	"rpg/gravestone",
	"rpg/greatsword",
	"rpg/helmet",
	"rpg/key",
	"rpg/knight",
	"rpg/mushroom",
	"rpg/pine_tree",
	"rpg/portal_gate",
	"rpg/potion_health",
	"rpg/potion_mana",
	"rpg/ring",
	"rpg/rock_large",
	"rpg/rock_small",
	"rpg/rune_stone",
	"rpg/scroll",
	"rpg/shield",
	"rpg/skull",
	"rpg/staff",
	"rpg/stalagmite",
	"rpg/stone_pillar",
	"rpg/sword",
	"rpg/torch",
	"siedler/bakery",
	"siedler/blacksmith",
	"siedler/castle",
	"siedler/coal_mine",
	"siedler/coal_node",
	"siedler/construction",
	"siedler/farm",
	"siedler/fishery",
	"siedler/flag",
	"siedler/fish_spot",
	"siedler/forester",
	"siedler/gold_mine",
	"siedler/gold_node",
	"siedler/iron_mine",
	"siedler/iron_node",
	"siedler/knight",
	"siedler/oak",
	"siedler/quarry",
	"siedler/sawmill",
	"siedler/settler",
	"siedler/smelter",
	"siedler/stone_node",
	"siedler/toolsmith",
	"siedler/warehouse",
	"siedler/watchtower",
	"siedler/windmill",
	"siedler/woodcutter",
	"ship",
	"tree",
	"xmas_bauble",
	"xmas_candy_cane",
	"xmas_gingerbread_star",
	"xmas_pinecone",
	"xmas_star",
]

## Sections of the gallery, in walking order.
const GROUPS: Array[Dictionary] = [
	{"id": "helden", "name": "Heroes & weapons", "icon": "⚔", "color": Color("94a3b8")},
	{"id": "drachen", "name": "Dragons", "icon": "☄", "color": Color("f472b6")},
	{"id": "metro", "name": "City & Metro", "icon": "▣", "color": Color("38bdf8")},
	{"id": "sammeln", "name": "Loot & gear", "icon": "◆", "color": Color("fbbf24")},
	{"id": "natur", "name": "Nature", "icon": "❦", "color": Color("4ade80")},
	{"id": "ruinen", "name": "Ruins & props", "icon": "▣", "color": Color("a78bfa")},
	{"id": "zucht", "name": "Breeding & eggs", "icon": "✦", "color": Color("f472b6")},
	{"id": "gegner", "name": "Enemies", "icon": "◉", "color": Color("f87171")},
	{"id": "pang", "name": "Pang objects", "icon": "⇈", "color": Color("fbbf24")},
	{"id": "merge", "name": "Merge & crystal tiers", "icon": "✦", "color": Color("38bdf8")},
	{"id": "siedler", "name": "Settler village", "icon": "⌂", "color": Color("84cc16")},
	{"id": "candy", "name": "Candy crush tiles", "icon": "✦", "color": Color("f472b6")},
]

## Breeding props of the hatchery.
const ZUCHT_KEYS: Array[String] = [
	"flight/egg", "flight/egg_large", "flight/egg_crystal",
	"flight/nest", "flight/pedestal", "flight/roost",
]

## Flying and ground enemies of the dragon-flight game.
const GEGNER_KEYS: Array[String] = [
	"flight/wyvern", "flight/imp", "flight/harpy", "flight/ballista", "flight/golem",
]

## Ball, harpoon, platform and the three bonus pickups of the Pang clone.
const PANG_KEYS: Array[String] = [
	"pang/orb", "pang/harpoon", "pang/platform",
	"pang/ice", "pang/clock", "pang/heart",
]

const MERGE_KEYS: Array[String] = [
	"crystal", "crystal1", "crystal2", "crystal3", "crystal4", "crystal5",
	"ornament", "pumpkin",
	"xmas_pinecone", "xmas_candy_cane", "xmas_bauble", "xmas_gingerbread_star", "xmas_star",
	"halloween_seed", "halloween_candy", "halloween_mini_pumpkin", "halloween_pumpkin", "halloween_ghost_pumpkin",
]

## Board pieces of the match-3 (candy + flower world plus one Xmas prop).
const CANDY_KEYS: Array[String] = [
	"candy/bonbon", "candy/lolly", "candy/jellybean",
	"candy/gumdrop", "candy/chocolate", "candy/heart",
	"candy/rose", "candy/tulip", "candy/sunflower",
	"candy/daisy", "candy/lily", "candy/lotus", "candy/gift",
]

const NATURE_KEYS: Array[String] = [
	"rpg/pine_tree", "rpg/dead_tree", "rpg/bush", "rpg/grass_tuft", "rpg/mushroom",
	"rpg/crystal_cluster", "rpg/stalagmite", "tree",
]

const TREASURE_KEYS: Array[String] = [
	"rpg/coin", "rpg/gem", "rpg/ring", "rpg/amulet", "rpg/shield", "rpg/helmet",
	"rpg/armor", "rpg/boots", "rpg/crown", "rpg/scroll", "rpg/key",
	"rpg/chest", "rpg/barrel", "rpg/crate", "rpg/potion_health", "rpg/potion_mana",
	"rpg/campfire", "rpg/torch",
]

const RUIN_KEYS: Array[String] = [
	"rpg/stone_pillar", "rpg/broken_pillar", "rpg/rune_stone", "rpg/gravestone",
	"rpg/dungeon_arch", "rpg/portal_gate", "rpg/skull", "rpg/bone_pile",
	"rpg/rock_small", "rpg/rock_large", "rock", "log", "fence",
]

## Buildings, rolling stock and infrastructure of the metro game.
const METRO_KEYS: Array[String] = [
	"metro/station", "metro/interchange", "metro/transfer_ring", "metro/loco",
	"metro/car", "metro/bridge", "metro/tunnel_portal", "metro/house",
	"metro/tower", "metro/park", "metro/passenger",
]

## Castle, production buildings, road flags, settlers and deposits of the
## Siedler game.
const SIEDLER_KEYS: Array[String] = [
	"siedler/castle", "siedler/warehouse", "siedler/construction", "siedler/flag",
	"siedler/settler", "siedler/knight",
	"siedler/woodcutter", "siedler/forester", "siedler/sawmill", "siedler/quarry",
	"siedler/farm", "siedler/windmill", "siedler/bakery", "siedler/fishery",
	"siedler/coal_mine", "siedler/iron_mine", "siedler/gold_mine", "siedler/smelter",
	"siedler/toolsmith", "siedler/blacksmith", "siedler/watchtower",
	"siedler/oak", "siedler/stone_node", "siedler/coal_node", "siedler/iron_node",
	"siedler/gold_node", "siedler/fish_spot",
]


# --- detail levels ----------------------------------------------------------
#
# Every mesh ships in three resolutions. `low` is the one the games use (a few
# hundred triangles, so the APK and every mobile GPU stay happy); `med` and
# `high` are generated from the same geometry by
# `scripts/blender/generate_lod_meshes.py` and exist for the mesh gallery, where
# you can compare a silhouette against a properly detailed version.
#
# Only the low tier is in the registry's `KEYS`; the richer tiers are derived, so
# adding a mesh automatically gives it all three levels.

const TIERS: Array[String] = ["low", "med", "high"]

## What the gallery calls the tiers.
##
## The values are the **source language** and nothing else: a literal in
## `godot/src` is English, and a German fallback here showed up as "Mittel" on
## an English screen and on a French one. `tier_label()` is what reads them, and
## it asks `TIER_LOC_KEY` first — the catalogue is the answer, these are what it
## falls back to while a translation is missing. "Low Poly" is the name of the
## technique itself and stays what it is in every language.
const TIER_LABELS := {
	"low": "Low Poly",
	"med": "Medium",
	"high": "High",
}

## The triangle budget each tier aims for.
##
## These are **floors, not the counts themselves**. The shipped `low` tier is
## refined to a per-mesh target committed in `godot/assets/meshes/low_target.json`
## (`scripts/blender/refine_low_meshes.py`), and `med`/`high` are then derived
## from whatever that produced (`scripts/blender/generate_lod_meshes.py`), each
## at least its floor here *and* at least a multiple of the low count. A flat
## 1000 would make the middle tier coarser than the tier below it for a mesh
## whose low tier costs more than that. The real numbers are measured into
## `lod.json` and displayed per mesh — read those, not this, to learn a count.
const TIER_BUDGET := {"low": 0, "med": 1000, "high": 10000}

const TIER_LOC_KEY := {
	"med": "gallery.tier.med",
	"high": "gallery.tier.high",
}

const GALLERY_LOC_KEYS: Array[String] = [
	"gallery.tier.med",
	"gallery.tier.high",
]

## Written by the Blender LOD generator; `{"<key>": {"low": n, "med": n, "high": n}}`.
const LOD_STATS := "%s/lod.json" % MESH_DIR

static var _tri_cache: Dictionary = {}
static var _tri_cache_loaded := false


## `res://` path of a mesh.
static func path_of(key: String) -> String:
	return "%s/%s.glb" % [MESH_DIR, key]


## `res://` path of one detail level. The low tier lives in the mesh root, the
## generated tiers in their own folders.
static func tier_path_of(key: String, tier: String) -> String:
	if tier == "low" or tier == "":
		return path_of(key)
	return "%s/%s/%s.glb" % [MESH_DIR, tier, key]


## True when the mesh is bundled and imported.
static func exists(key: String) -> bool:
	return ResourceLoader.exists(path_of(key))


## True when one detail level is available. A key always has `low`; the richer
## tiers only exist once the generator has run.
static func tier_exists(key: String, tier: String) -> bool:
	return ResourceLoader.exists(tier_path_of(key, tier))


## The finest level that is actually present, never finer than `tier`.
##
## `TIERS` is ordered coarse → fine, so the candidates have to be walked
## **backwards**: a request for `high` looks at `high` first and only falls back
## to `med` and then `low`. Walking forwards returned `low` for every single
## request, because `low` sits at index 0 and therefore always satisfies
## "coarser than high" — so the gallery stood a low-poly mesh under the heading
## "High", printed its "instead of" notice on every pedestal at every level and
## quoted the low triangle count, while 310 `.glb` files nobody ever loaded
## shipped in the APK.
static func best_available(key: String, tier: String) -> String:
	# An unknown or empty tier asks for the coarsest level, which is the one
	# every mesh is promised to have.
	var wanted := maxi(TIERS.find(tier), 0)
	for i in range(wanted, -1, -1):
		var candidate: String = TIERS[i]
		if tier_exists(key, candidate):
			return candidate
	# Nothing on disk at all: `low` is the last resort, and the caller falls
	# back to a procedural primitive beyond that.
	return "low"


## Measured triangle counts per key, read once from the generator's stats file.
static func tri_counts() -> Dictionary:
	if _tri_cache_loaded:
		return _tri_cache
	_tri_cache_loaded = true
	_tri_cache = {}
	if not FileAccess.file_exists(LOD_STATS):
		return _tri_cache
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(LOD_STATS))
	if parsed is Dictionary:
		for key in parsed:
			_tri_cache[str(key)] = (parsed as Dictionary)[key]
	return _tri_cache


## Triangle count of one level, or -1 when the generator has not run.
static func tri_count(key: String, tier: String) -> int:
	var entry: Variant = tri_counts().get(key)
	if not (entry is Dictionary):
		return -1
	return int((entry as Dictionary).get(tier, -1))


## `1.240 Dreiecke`, or an em dash when the count is unknown.
static func tri_text(key: String, tier: String) -> String:
	var count := tri_count(key, tier)
	return "—" if count < 0 else Ui.format_number(count)


## The tier's name in the player's language, for every place that shows one.
static func tier_label(tier: String) -> String:
	var key := str(TIER_LOC_KEY.get(tier, ""))
	if key != "":
		return Loc.t(key)
	return str(TIER_LABELS.get(tier, tier))


## Display name for a key, derived from the file name.
static func display_name(key: String) -> String:
	var raw := key.get_file().replace("_", " ")
	var words := raw.split(" ")
	for i in words.size():
		words[i] = words[i].capitalize()
	return " ".join(words)


## Which gallery section a key belongs to.
static func group_of(key: String) -> String:
	if key.begins_with("rpg/dragon_") or key.begins_with("flight/dragon_"):
		return "drachen"
	if key in ZUCHT_KEYS:
		return "zucht"
	if key in METRO_KEYS:
		return "metro"
	if key in SIEDLER_KEYS:
		return "siedler"
	if key in GEGNER_KEYS:
		return "gegner"
	if key in PANG_KEYS:
		return "pang"
	if key in ["rpg/knight", "horse", "rpg/sword", "rpg/greatsword", "rpg/dagger", "rpg/axe", "rpg/staff", "rpg/bow", "ship"]:
		return "helden"
	if key in CANDY_KEYS:
		return "candy"
	if key in MERGE_KEYS:
		return "merge"
	if key in NATURE_KEYS:
		return "natur"
	if key in TREASURE_KEYS:
		return "sammeln"
	if key in RUIN_KEYS:
		return "ruinen"
	# Everything else in the flight pack is sky scenery (clouds, islands, totems).
	if key.begins_with("flight/"):
		return "natur"
	return "helden"


## Keys of one section, in registry order.
static func keys_in_group(group_id: String) -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if group_of(key) == group_id:
			out.append(key)
	return out


# --- standard colours -------------------------------------------------------

## What a key wears when nothing more specific was chosen for it. A neutral
## slate rather than a colour: this is the colour of a mesh nobody has looked at
## yet, and the point of the table below is that there are as few of those as
## possible.
const DEFAULT_COLOR := Color("94a3b8")

## The standard colour of every bundled mesh, written out.
##
## A player wrote: "can there be Standard colors vor the meshes? they seem to
## have random colours". They were right, and the reason was a line of code:
## `color_of()` hashed the key and read the hue out of the hash. So the knight
## stood lime green, the horse magenta and the campfire whatever the letters of
## its own name happened to add up to — and because the hue came from the
## spelling, adding one mesh in the middle of the alphabet silently repainted
## its neighbours. A lime-green knight and a magenta horse are not "random
## colours" in the eye: they are objects that stopped looking like what they
## are, one pedestal next to the other.
##
## So the colour is **chosen**, and the choice lives in data. Three rules:
##
## - It is stable. The same key wears the same colour on every device, in every
##   run and in every build — which is what the hash was supposed to buy, and
##   what it could not, because a hash is stable but not *chosen*.
## - It is per family, not per spelling. A dragon is red because it is a dragon
##   and its element says which red; a coin is gold and a rune stone is violet.
## - A new key needs no entry. It wears its gallery section's colour
##   (`GROUPS`), so nothing that lands in this table later can look random
##   again. That is the whole reason the fallback exists and the only reason a
##   missing entry is not a bug.
const STANDARD_COLORS := {
	# --- heroes & weapons: steel, wood and leather, not paint ---
	"rpg/knight": Color("cbd5e1"),
	"horse": Color("92400e"),
	"ship": Color("92400e"),
	"rpg/sword": Color("cbd5e1"),
	"rpg/greatsword": Color("e2e8f0"),
	"rpg/dagger": Color("94a3b8"),
	"rpg/axe": Color("b45309"),
	"rpg/staff": Color("a78bfa"),
	"rpg/bow": Color("b45309"),
	"rpg/shield": Color("64748b"),
	"rpg/helmet": Color("94a3b8"),
	"rpg/armor": Color("64748b"),
	"rpg/boots": Color("92400e"),
	"rpg/crown": Color("facc15"),

	# --- dragons: the element names the colour ---
	"rpg/dragon_lord": Color("dc2626"),
	"rpg/dragon_elder": Color("e11d48"),
	"rpg/dragon_ember": Color("f97316"),
	"rpg/dragon_frost": Color("7dd3fc"),
	"rpg/dragon_gold": Color("fbbf24"),
	"rpg/dragon_hatchling": Color("34d399"),
	"rpg/dragon_shadow": Color("7c3aed"),
	"rpg/dragon_stone": Color("94a3b8"),
	"rpg/dragon_storm": Color("a78bfa"),
	"rpg/dragon_venom": Color("84cc16"),
	"rpg/dragon_bone": Color("e7e5e4"),
	"rpg/dragon_crystal": Color("67e8f9"),
	"flight/dragon_cloud": Color("e2e8f0"),
	"flight/dragon_solar": Color("fcd34d"),
	"flight/dragon_tide": Color("38bdf8"),
	"flight/dragon_void": Color("a855f7"),

	# --- sky, breeding and the flying enemies ---
	"flight/ballista": Color("b45309"),
	"flight/cloud": Color("f1f5f9"),
	"flight/cloud_storm": Color("94a3b8"),
	"flight/egg": Color("fef3c7"),
	"flight/egg_large": Color("fde68a"),
	"flight/egg_crystal": Color("67e8f9"),
	"flight/fireball": Color("f97316"),
	"flight/golem": Color("78716c"),
	"flight/harpy": Color("c4b5fd"),
	"flight/imp": Color("ef4444"),
	"flight/island": Color("4ade80"),
	"flight/nest": Color("b45309"),
	"flight/pedestal": Color("94a3b8"),
	"flight/roost": Color("a16207"),
	"flight/totem": Color("d6d3d1"),
	"flight/wyvern": Color("10b981"),

	# --- city & metro: concrete, steel and the two liveries ---
	"metro/station": Color("94a3b8"),
	"metro/interchange": Color("64748b"),
	"metro/transfer_ring": Color("38bdf8"),
	"metro/loco": Color("dc2626"),
	"metro/car": Color("2563eb"),
	"metro/bridge": Color("78716c"),
	"metro/tunnel_portal": Color("475569"),
	"metro/house": Color("cbd5e1"),
	"metro/tower": Color("a8a29e"),
	"metro/park": Color("4ade80"),
	"metro/passenger": Color("f59e0b"),

	# --- settler village: earth, timber, and a colour per deposit ---
	"siedler/castle": Color("e2e8f0"),
	"siedler/warehouse": Color("d6d3d1"),
	"siedler/construction": Color("fbbf24"),
	"siedler/flag": Color("94a3b8"),
	"siedler/settler": Color("f59e0b"),
	"siedler/knight": Color("cbd5e1"),
	"siedler/woodcutter": Color("b45309"),
	"siedler/forester": Color("15803d"),
	"siedler/sawmill": Color("a16207"),
	"siedler/quarry": Color("a8a29e"),
	"siedler/farm": Color("4ade80"),
	"siedler/windmill": Color("e7e5e4"),
	"siedler/bakery": Color("d97706"),
	"siedler/fishery": Color("0ea5e9"),
	"siedler/coal_mine": Color("334155"),
	"siedler/iron_mine": Color("57534e"),
	"siedler/gold_mine": Color("ca8a04"),
	"siedler/smelter": Color("78716c"),
	"siedler/toolsmith": Color("64748b"),
	"siedler/blacksmith": Color("57534e"),
	"siedler/watchtower": Color("a8a29e"),
	"siedler/oak": Color("15803d"),
	"siedler/stone_node": Color("a8a29e"),
	"siedler/coal_node": Color("334155"),
	"siedler/iron_node": Color("94a3b8"),
	"siedler/gold_node": Color("fbbf24"),
	"siedler/fish_spot": Color("38bdf8"),

	# --- pang objects: the ball, the harpoon and the three bonuses ---
	"pang/orb": Color("f87171"),
	"pang/harpoon": Color("94a3b8"),
	"pang/platform": Color("475569"),
	"pang/ice": Color("bae6fd"),
	"pang/clock": Color("fbbf24"),
	"pang/heart": Color("fb7185"),

	# --- nature ---
	"rpg/pine_tree": Color("15803d"),
	"rpg/dead_tree": Color("78716c"),
	"rpg/bush": Color("4ade80"),
	"rpg/grass_tuft": Color("4ade80"),
	"rpg/mushroom": Color("ef4444"),
	"rpg/crystal_cluster": Color("22d3ee"),
	"rpg/stalagmite": Color("94a3b8"),
	"tree": Color("15803d"),

	# --- loot & gear ---
	"rpg/coin": Color("fbbf24"),
	"rpg/gem": Color("38bdf8"),
	"rpg/ring": Color("fcd34d"),
	"rpg/amulet": Color("c084fc"),
	"rpg/chest": Color("92400e"),
	"rpg/barrel": Color("b45309"),
	"rpg/crate": Color("b45309"),
	"rpg/scroll": Color("fef3c7"),
	"rpg/key": Color("fcd34d"),
	"rpg/potion_health": Color("ef4444"),
	"rpg/potion_mana": Color("3b82f6"),
	"rpg/campfire": Color("f97316"),
	"rpg/torch": Color("fb923c"),

	# --- ruins & props ---
	"rpg/stone_pillar": Color("a8a29e"),
	"rpg/broken_pillar": Color("a8a29e"),
	"rpg/rune_stone": Color("a78bfa"),
	"rpg/gravestone": Color("78716c"),
	"rpg/dungeon_arch": Color("94a3b8"),
	"rpg/portal_gate": Color("8b5cf6"),
	"rpg/skull": Color("e7e5e4"),
	"rpg/bone_pile": Color("e7e5e4"),
	"rpg/rock_small": Color("a8a29e"),
	"rpg/rock_large": Color("a8a29e"),
	"rock": Color("a8a29e"),
	"log": Color("92400e"),
	"fence": Color("b45309"),

	# --- candy: a bonbon is pink and a chocolate is brown ---
	"candy/bonbon": Color("f472b6"),
	"candy/chocolate": Color("92400e"),
	"candy/daisy": Color("f8fafc"),
	"candy/gift": Color("ef4444"),
	"candy/gumdrop": Color("fbbf24"),
	"candy/heart": Color("fb7185"),
	"candy/jellybean": Color("a78bfa"),
	"candy/lily": Color("e2e8f0"),
	"candy/lolly": Color("f87171"),
	"candy/lotus": Color("f9a8d4"),
	"candy/rose": Color("f43f5e"),
	"candy/sunflower": Color("facc15"),
	"candy/tulip": Color("fb923c"),

	# --- merge tiers, crystals and the two party seasons ---
	# The crystal ramp climbs from cyan to violet in tier order, because the
	# board reads it: a higher tier has to look like the same stone cut finer.
	"crystal": Color("22d3ee"),
	"crystal1": Color("38bdf8"),
	"crystal2": Color("60a5fa"),
	"crystal3": Color("818cf8"),
	"crystal4": Color("a78bfa"),
	"crystal5": Color("c084fc"),
	"ornament": Color("e11d48"),
	"pumpkin": Color("f97316"),
	"xmas_pinecone": Color("92400e"),
	"xmas_candy_cane": Color("ef4444"),
	"xmas_bauble": Color("dc2626"),
	"xmas_gingerbread_star": Color("d97706"),
	"xmas_star": Color("fbbf24"),
	"halloween_seed": Color("84cc16"),
	"halloween_candy": Color("f472b6"),
	"halloween_mini_pumpkin": Color("fb923c"),
	"halloween_pumpkin": Color("f97316"),
	"halloween_ghost_pumpkin": Color("e2e8f0"),
}


## The standard colour of `key`: its own entry from `STANDARD_COLORS`, and
## otherwise the colour of the gallery section it stands in.
##
## Two steps, deliberately. The second one is why a mesh nobody has thought about
## yet still looks deliberate — it arrives in its section's colour, the same one
## the player navigates by — and it is also why there is no third step. A hash
## used to stand here, and it is what made the hall look like a paint mixer:
## stable, reproducible, and completely unchosen.
static func color_of(key: String) -> Color:
	if STANDARD_COLORS.has(key):
		return STANDARD_COLORS[key]
	return group_color(group_of(key))


## The colour of one gallery section, `DEFAULT_COLOR` for an id nobody knows.
static func group_color(group_id: String) -> Color:
	for group in GROUPS:
		if str(group.get("id", "")) == group_id:
			return group.get("color", DEFAULT_COLOR)
	return DEFAULT_COLOR


# --- a colour you can read ----------------------------------------------------

## How dark a standard colour may be before the name written in it stops being
## readable, as a WCAG contrast ratio against `LABEL_BACKGROUND`.
##
## Not the 4.5:1 of WCAG AA, and the reason is the thing itself: a pedestal sign
## is a 44 px `Label3D` with a 14 px outline, and a thick outline is exactly the
## technique for putting text on a background you do not control. 2.5:1 is where
## the sign stops reading as "faint" and starts reading as "absent" — measured on
## the standard palette, 13 of the 155 colours fall below it.
const LABEL_MIN_CONTRAST := 2.5
## The colour a pedestal sign is measured against: the hall's wall. The floor is
## darker still (`111827`) and the outline darker again (`020617`), so the wall is
## the generous reading of the same background.
const LABEL_BACKGROUND := Color("1f2937")
## How much lightness one round of `label_color()` spends. Sized from the
## palette: 13 colours need lifting and the darkest of them, a coal node, is
## clear of the floor after two rounds.
const LABEL_LIFT := 0.12


## The colour to *write* a mesh's name in — a different question from the colour
## the mesh wears.
##
## A coal node is genuinely almost black, and against a dark hall that name is
## unreadable at 1.4:1. Repainting the coal node grey so its own label can be
## read would be solving the wrong problem: the label is what adapts, not the
## thing. So the hue is kept and the lightness is spent until the contrast clears
## the floor — a coal node's sign stays a recognisable blue-grey, only legible.
static func label_color(key: String) -> Color:
	var color := color_of(key)
	# Bounded, because this walks data: a palette entry dark enough to need a
	# dozen rounds should reach the floor long before the guard does, and the
	# guard is what keeps a bad entry from spinning here instead of failing.
	var rounds := 0
	while contrast_ratio(color, LABEL_BACKGROUND) < LABEL_MIN_CONTRAST and rounds < 8:
		color = color.lightened(LABEL_LIFT)
		rounds += 1
	return color


## WCAG 2.1 contrast ratio of two sRGB colours: 1.0 for identical, 21.0 for
## black on white.
##
## `srgb_to_linear()` is the conversion Godot's own lighting does, and
## `get_luminance()` is the Rec.709 dot product the WCAG definition uses — so
## this is the standard's own arithmetic, not an approximation of it. It costs
## four `pow()` calls and is only reached from the label path: once per pedestal
## at build time and once per info card at 10 Hz, never in `_process`.
static func contrast_ratio(a: Color, b: Color) -> float:
	var la := a.srgb_to_linear().get_luminance()
	var lb := b.srgb_to_linear().get_luminance()
	return (maxf(la, lb) + 0.05) / (minf(la, lb) + 0.05)


## Every colour `color_of()` can answer with, deduplicated and built once.
##
## A *closed* set, and that is what makes it worth having: the mesh gallery is
## the only consumer, and a test can hold every key against this list to prove
## that no colour ever reaches a pedestal that nobody picked. A hash cannot be
## checked that way, which is how "random colours" survived in a green suite for
## as long as it did.
static var _palette: Array[Color] = []


static func standard_palette() -> Array[Color]:
	if not _palette.is_empty():
		return _palette
	for key in KEYS:
		var color := color_of(key)
		if not (color in _palette):
			_palette.append(color)
	return _palette


## Keys the registry promises but the folder does not deliver.
static func missing() -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if not exists(key):
			out.append(key)
	return out


## Meshes present on disk that the registry forgot.
static func unlisted() -> Array[String]:
	var out: Array[String] = []
	for key in _on_disk():
		if not (key in KEYS):
			out.append(key)
	return out


## Every `.glb` key found in the mesh folder, ignoring the generated tier
## folders — those mirror the low tier and are not separate meshes.
static func _on_disk() -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open(MESH_DIR)
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if dir.current_is_dir():
			if not name.begins_with(".") and not (name in TIERS):
				out.append_array(_sub_keys(name))
		elif name.ends_with(".glb"):
			out.append(name.substr(0, name.length() - 4))
		name = dir.get_next()
	dir.list_dir_end()
	out.sort()
	return out


static func _sub_keys(folder: String) -> Array[String]:
	var out: Array[String] = []
	var dir := DirAccess.open("%s/%s" % [MESH_DIR, folder])
	if dir == null:
		return out
	dir.list_dir_begin()
	var name := dir.get_next()
	while name != "":
		if not dir.current_is_dir() and name.ends_with(".glb"):
			out.append("%s/%s" % [folder, name.substr(0, name.length() - 4)])
		name = dir.get_next()
	dir.list_dir_end()
	return out


## Keys that do not have this detail level, `[]` once the generator has run.
##
## Every tier is checked, `low` included: it used to return `[]` for `low`
## without looking at a single file, which made an assertion on it vacuous —
## the suite proved nothing about the 155 low-poly meshes it claimed to check.
##
## **The real gate is the two generated tiers:** after
## `scripts/blender/generate_lod_meshes.py` has run, `tiers_missing("med")` and
## `tiers_missing("high")` must both be empty. `tiers_missing("low")` empty only
## says the registry and the mesh folder agree; it says nothing about the two
## levels the gallery exists to show.
##
## A tier nobody has — a typo, or one the build skipped — has no files at all,
## so every key is reported for it. That is the answer to the question asked.
static func tiers_missing(tier: String) -> Array[String]:
	var out: Array[String] = []
	for key in KEYS:
		if not tier_exists(key, tier):
			out.append(key)
	return out
